# Path to the dataset
path: /davinci-1/home/msarti/projects/AGRARIAN/data/Aerial_Sheep_v1

# Train, validation, and test image directories
train: train/images
val: valid/images
test: test/images

# Number of classes
nc: 1

# Class names
names: ['sheep']
