# https://sdk-forum.dji.net/hc/en-us/articles/12325496609689-What-is-the-custom-camera-parameters-for-Mavic-3-Enterprise-series-and-Mavic-3M

# positive float: true focal lenght of the camera in mm
true_focal_len_mm: 12.29

# positive float: width of the camera sensor in millimeters
sensor_width_mm: 17.35 # standard for 4/3 CMOS sensor

# positive float: height of the camera sensor in millimeters
sensor_height_mm: 13.00  # standard for 4/3 CMOS sensor

# positive int: width of the camera sensor in pixels
sensor_width_pixels: 5280 # standard Effective 20MP for 4/3 CMOS sensor

# positive int: height of the camera sensor in pixels
sensor_height_pixels: 3956  # standard Effective 20MP for 4/3 CMOS sensor

# NOTE: sensor_width_pixels/sensor_height_pixels MUST be equal to sensor_width_mm/sensor_height_mm

# These are only used for streams, precise values are used when video files are opened instead
frame_height: 1080
frame_width: 1920
fps: 30