# Example Training Configuration

model: yolo11m.pt  # Path to Model checkpoint (.pt), str, path exists
data: data/Aerial_Sheep_v1/data.yaml  # Path to dataset config file (.yaml), str, path exists
epochs: 20  # Number of training epochs, int, [0, inf)
time: null  # Max training time in hours (optional), if set overrides 'epochs', null or float, > 0 if float
patience: 20  # Early stopping patience, int (0,epochs]
batch: 16  # Batch size, int or float, -1 for 60% of gpu usage, int >=0, or float in (0.0, 1.0] per dataset percentage
imgsz: 640  # Image size for training, int, >= 32
save: true  # Enable saving of checkpoints, bool
save_period: 10  # Save model checkpoints every 'save_period' epochs, int, (0, epochs]
cache: false  # Cache dataset images in memory, faster training but more memory required, bool
device: 3  # Device: 'cpu', gpu_id, or list of gpu_ids for distributed training, str or int >=0 or list of ints >=0
workers: 8  # Number of worker threads for data loading, int, >=0
project: experiments  # Project directory name for outputs, str
name: example_train_run # name of the run, str
exist_ok: true  # Allow overwriting existing project/name directory, bool
pretrained: true  # Start from a pretrained model, bool
optimizer: auto  # Optimizer, str, [SGD, Adam, ...]
verbose: false  # Enable verbose output, bool
seed: 0  # Random seed, int, >=0
deterministic: true  # Use deterministic algorithms for reproducibility, bool
single_cls: true  # Treat all classes as a single class, bool
rect: false  # Enable rectangular training, bool
cos_lr: true  # Use cosine learning rate scheduler, bool
close_mosaic: 10  # Disable mosaic augmentation in last N epochs, int, [0, epochs]
resume: false  # Resume from checkpoint, bool
amp: true  # Enable Automatic Mixed Precision (AMP) training, bool
fraction: 1.0  # Fraction of dataset to use, float (0.0, 1.0]
profile: false  # Enable profiling (ONNX/TensorRT speeds), bool
freeze: null  # Freezes the first N layers of the model or specified layers by index, ?, ?

# Learning Rate and Optimization Parameters
lr0: 0.01  # Initial learning rate, float, >0
lrf: 0.01  # Final learning rate (as fraction of lr0),  float, >0
momentum: 0.937  # Momentum (SGD/beta1 for Adam), float, [0.0, 1.0]
weight_decay: 0.0005  # Weight decay (L2 regularization), float, >=0
warmup_epochs: 3  # Warmup epochs, int, >=0
warmup_momentum: 0.8  # Initial momentum for warmup, float, [0.0, 1.0]
warmup_bias_lr: 0.1  # Bias learning rate during warmup, float, >=0

# Loss Function Weights
box: 7.5  # Box loss weight, float, >=0
cls: 0.5  # Classification loss weight, float, >=0
dfl: 1.5  # Distribution focal loss weight, float, >=0
pose: 12.0  # Pose loss weight (for pose estimation), float, >=0
kobj: 2.0  # Keypoint objectness loss (pose estimation), float, >=0

# Label Smoothing and Regularization
label_smoothing: 0.0  # Label smoothing, float, [0.0, 1.0)
nbs: 64  # Nominal batch size, int, >=0
overlap_mask: true  # Allow overlapping masks in segmentation, bool
mask_ratio: 4  # Downsample ratio for masks, int, >=0
dropout: 0.0  # Dropout rate, float, [0.0, 1.0)

# Validation and Plotting
val: true  # Enable validation, bool
plots: true  # Generate training/validation metric plots, bool

# Augmentation Parameters
augment: true
hsv_h: 0.015  # Hue adjustment, float, [0.0, 1.0]
hsv_s: 0.7  # Saturation adjustment, float, [0.0, 1.0]
hsv_v: 0.4  # Brightness adjustment, float [0.0, 1.0]
degrees: 0.0  # Image rotation, int, [-180, +180]
translate: 0.1  # Image translation, float, [0.0, 1.0]
scale: 0.5  # Image scaling factor, float, >= 0.0
shear: 0.0  # Shear degree, float, [-180, +180]
perspective: 0.0  # Perspective transformation, float [0.0, 0.001]
flipud: 0.0  # Upside down flip probability, float, [0.0, 1.0]
fliplr: 0.5  # Left-right flip probability, float, [0.0, 1.0]
bgr: 0.0  # RGB to BGR channel flip probability, float, [0.0, 1.0]
mosaic: 1.0  # Mosaic augmentation, float, [0.0, 1.0]
mixup: 0.0  # Mixup augmentation, float, [0.0, 1.0]
copy_paste: 0.0  # Copy-paste augmentation, float, [0.0, 1.0]
copy_paste_mode: flip  # Copy-paste mode, str, [flip, mixup]
auto_augment: randaugment  # Auto augmentation policy, str, [randaugment, autoaugment, augmix]
erasing: 0.4  # Random erasing probability, float, [0.0, 0.9]
crop_fraction: 1.0  # Image cropping fraction, float, [0.1, 1.0]
