# str: Data source (a video) for in-danger analysis.
source: 'data/MAICH_v1/DJI_20241024104935_0008_D.MP4'

# str: Drone metadata file (.srt)
flight_data: 'data/MAICH_v1/DJI_20241024104935_0008_D.SRT'

# int: Frame stride for video inputs.
# Allows skipping frames to speed up inference. Higher values skip more frames.
# Range: Any positive integer.
vid_stride: 3

# int: Minimum number of seconds between alerts
alerts_cooldown_seconds: 1

# int: length of the tracking window
time_window_size: 100

# str: graph creation strategy, can be ['knn', 'radius', null]
graph_strategy: 'knn'

# int: how many neighbours to connect when using graph_strategy: 'knn'
graph_knn_neighbours: 10

# float: radius in meters used to connect with neighbours when using graph_strategy: 'radius'
graph_radius_meters: 10.0

