# str: Data source (a video) for in-danger analysis.
source: '/archive/group/ai/datasets/AGRARIAN/MAICH_v1/DJI_20241024104935_0008_D.MP4'

# str: Drone metadata file (.srt)
flight_data: '/archive/group/ai/datasets/AGRARIAN/MAICH_v1/DJI_20241024104935_0008_D.SRT'

# str: Path to the DEM data
# dem: '/archive/group/ai/datasets/AGRARIAN/DEM/merged/merged.tif'
dem: '/archive/group/ai/datasets/AGRARIAN/DEM/Copernicus_DSM_04_N35_00_E024_00_DEM.tif'

# str or null: Path to the DEM data mask, if null assumes all pixels are valid
# dem_mask: '/archive/group/ai/datasets/AGRARIAN/DEM/merged/merged_mask.tif'
dem_mask: null

# int: Frame stride for video inputs.
# Allows skipping frames to speed up inference. Higher values skip more frames.
# Range: Any positive integer.
vid_stride: 3

# float: radius of the of the safety around each sheep/goats, in meters
safety_radius_m: 1.5

# float: slope angle after which the portion of terrain is considered dangerous for the animals
slope_angle_threshold: 30.0

# set of tuples (longitude, latitude) defining the points marking the vertexes of the geofencing area
geofencing_vertexes:
  - [ 21.200000, 34.0 ]
  - [ 24.174019, 34.0 ]
  - [ 24.174019, 36.0 ]
  - [ 21.200000, 36.0 ]

# int: Minimum number of seconds between alerts
alerts_cooldown_seconds: 1
