# str: Name of the directory where the results of the analysis will be saved
output_dir: 'experiments/test_in_danger_final_parallel'

# str: Name of the files on which alerts will be saved
alert_file_name: 'alerts'

# str: Name of the video showing the annotated original data (with/without sheep count and tracks)
annotated_video_name: 'in_danger_annotated'