# Segmenter Configuration

# str: Path to the model checkpoint file.
# Specifies the .onnx file for the model to be used during inference.
model_checkpoint: 'checkpoints/in_danger/segmentation.onnx'

# list[int] or null: Indexes of classes to ignore
suppress_classes: null
