task: detect
model: "/davinci-1/home/msarti/projects/AGRARIAN_PROJECT/AGRARIAN/yolo11m.pt"

project: experiments
name: hs_optimized_yolo11m_1280_720
device:
  - 0
  - 1
  - 2
  - 3

lr0: 0.000375039007100781
momentum: 0.9789181818301523
weight_decay: 0.007733130245871337
dropout: 0.2847281200546442
box: 11.606287267702124
cls: 0.5788341469215824
dfl: 7.020438430907101
data: "/archive/group/ai/datasets/AGRARIAN/manual_annotations/train_val_test_splitted_1280_720/data.yaml"
epochs: 300
time: null
patience: 20
batch: 16
imgsz: 480
save: true
save_period: 25
cache: false
workers: 12
exist_ok: true
pretrained: true
optimizer: "AdamW"
seed: 0
deterministic: true
single_cls: false
classes: null
rect: false
cos_lr: true
close_mosaic: 20
amp: true
fraction: 1.0
profile: false
freeze: null
nbs: 64
val: true
plots: true
bgr: 0.0
lrf: 0.01
warmup_epochs: 10
warmup_momentum: 0.9
warmup_bias_lr: 0.05
hsv_h: 0.015
hsv_s: 0.75
hsv_v: 0.4
degrees: 180.0
translate: 0.2
scale: 0.25
shear: 5.0
perspective: 0.0
flipud: 0.5
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
cutmix: 0.0
resume: false
