# RTSP configuration (Annotated data)
rtsp: yes
rtspAddress: :8554 # Default RTSP port
protocols: [tcp, udp]

# RTMP configuration (drone RTMP video stream)
rtmp: yes
rtmpAddress: :1935  # Default RTMP port

webrtc: yes
webrtcAddress: :8889
webrtcICEServers: # STUN servcer needed for WebRTC to work across different networks (NAT traversal)
  - stun:stun.l.google.com:19302

# connection timeouts
readTimeout: 10s
writeTimeout: 10s

paths:
  # drone video in
  drone:
    source: publisher 
  # application stream out
  annot:
    source: publisher